"""Integration-тесты admin-CRUD webhook-подписок (E10-8 PR-A #198) — требуют Postgres.

Покрывают: create/list `webhooks`; RBAC (контракт: `staff_admin`; не-админ → 403);
**секрет отдаётся только при создании, в списке его нет** (ADR-0015 У6 / ФЗ-152);
автогенерация секрета; валидация events (пусто/неизвестное → 422), url, extra=forbid.
Принципал инжектится через `app.dependency_overrides` (seam #6).
"""

from __future__ import annotations

import asyncio
import os
import uuid
from collections.abc import AsyncIterator, Iterator

import pytest
from fastapi.testclient import TestClient
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine
from sqlalchemy.pool import NullPool

from api.auth.dependencies import get_current_principal
from api.auth.principal import Principal, PrincipalKind
from api.auth.scopes import STAFF_ADMIN_SCOPE
from api.config import get_settings
from api.db import get_session
from api.main import app
from api.tickets.enums import TicketTeam

pytestmark = pytest.mark.skipif(
    "CI" not in os.environ and "POSTGRES_AVAILABLE" not in os.environ,
    reason="CRUD webhooks требует живой Postgres (CI service container / POSTGRES_AVAILABLE=1).",
)

_ADMIN = Principal(
    user_id=uuid.uuid4(),
    kind=PrincipalKind.OPERATOR,
    scopes=frozenset({STAFF_ADMIN_SCOPE}),
    teams=frozenset({TicketTeam.SUPPORT}),
)
_OPERATOR = Principal(user_id=uuid.uuid4(), kind=PrincipalKind.OPERATOR)

_WEBHOOKS = "/api/v1/support/webhooks"


def _use(principal: Principal) -> None:
    app.dependency_overrides[get_current_principal] = lambda: principal


@pytest.fixture(autouse=True)
def _override_db_session() -> Iterator[None]:
    engine = create_async_engine(get_settings().database_url, poolclass=NullPool)
    factory = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    async def _get_test_session() -> AsyncIterator[AsyncSession]:
        async with factory() as session:
            try:
                yield session
            except Exception:
                await session.rollback()
                raise

    app.dependency_overrides[get_session] = _get_test_session
    yield
    app.dependency_overrides.pop(get_session, None)
    app.dependency_overrides.pop(get_current_principal, None)
    asyncio.run(engine.dispose())


@pytest.fixture
def client() -> Iterator[TestClient]:
    with TestClient(app) as test_client:
        yield test_client


def test_create_returns_secret_and_list_hides_it(client: TestClient) -> None:
    _use(_ADMIN)
    create = client.post(
        _WEBHOOKS,
        json={
            "url": "https://subscriber.example.com/hook",
            "events": ["ticket.case_decided", "ticket.payout_released"],
            "secret": "supersecretvalue-1234",
        },
    )
    assert create.status_code == 201, create.text
    data = create.json()["data"]
    sub_id = data["id"]
    assert data["secret"] == "supersecretvalue-1234"  # секрет — в ответе создания
    assert data["events"] == ["ticket.case_decided", "ticket.payout_released"]
    assert data["is_active"] is True

    listed = client.get(_WEBHOOKS)
    assert listed.status_code == 200
    item = next(i for i in listed.json()["data"] if i["id"] == sub_id)
    # ADR-0015 У6: секрет НЕ отдаётся в списке.
    assert "secret" not in item
    assert item["url"] == "https://subscriber.example.com/hook"


def test_secret_autogenerated_when_omitted(client: TestClient) -> None:
    _use(_ADMIN)
    resp = client.post(
        _WEBHOOKS,
        json={"url": "https://x.example.com/h", "events": ["ticket.created"]},
    )
    assert resp.status_code == 201, resp.text
    secret = resp.json()["data"]["secret"]
    assert isinstance(secret, str) and len(secret) >= 32  # сгенерирован сервером


def test_rbac_non_admin_forbidden(client: TestClient) -> None:
    _use(_OPERATOR)
    assert client.get(_WEBHOOKS).status_code == 403
    create = client.post(
        _WEBHOOKS, json={"url": "https://x.example.com/h", "events": ["ticket.created"]}
    )
    assert create.status_code == 403


def test_validation_rejects_empty_and_unknown_events(client: TestClient) -> None:
    _use(_ADMIN)
    empty = client.post(_WEBHOOKS, json={"url": "https://x.example.com/h", "events": []})
    assert empty.status_code == 422, empty.text
    unknown = client.post(
        _WEBHOOKS, json={"url": "https://x.example.com/h", "events": ["ticket.not_a_real_event"]}
    )
    assert unknown.status_code == 422, unknown.text


def test_validation_rejects_bad_url_and_extra(client: TestClient) -> None:
    _use(_ADMIN)
    bad_url = client.post(_WEBHOOKS, json={"url": "not-a-url", "events": ["ticket.created"]})
    assert bad_url.status_code == 422, bad_url.text
    extra = client.post(
        _WEBHOOKS,
        json={"url": "https://x.example.com/h", "events": ["ticket.created"], "rogue": 1},
    )
    assert extra.status_code == 422, extra.text
