/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/support/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список заявок
         * @description Возвращает заявки с фильтрами и cursor-пагинацией. Видимость зависит от scope: заявитель видит только свои; оператор — по своей команде/scope (фильтрация на уровне хранилища, ADR-0003).
         */
        get: operations["listTickets"];
        put?: never;
        /** Создать заявку */
        post: operations["createTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/support/tickets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Карточка заявки
         * @description Заявитель видит только свою. Недоступная заявка → 404 (ADR-0003).
         */
        get: operations["getTicket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Обновить заявку
         * @description Статус, приоритет, тип, команда, теги. Недопустимый переход статуса → 409.
         */
        patch: operations["updateTicket"];
        trace?: never;
    };
    "/api/v1/support/tickets/{id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Назначить заявку */
        post: operations["assignTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/support/tickets/{id}/escalate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Эскалировать на 2-ю линию */
        post: operations["escalateTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/support/tickets/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отметить решённой */
        post: operations["resolveTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/support/tickets/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Закрыть заявку */
        post: operations["closeTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/support/tickets/{id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Переоткрыть заявку */
        post: operations["reopenTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/support/tickets/{id}/rate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Оценка заявителя
         * @description Доступно заявителю после RESOLVED/CLOSED. Оценка 1-2 уведомляет супервайзера.
         */
        post: operations["rateTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/support/tickets/{id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Решение по претензии
         * @description Оформляет решение по претензионному обращению (COMPENSATION): полная/частичная выплата или отказ. Уведомляет обе стороны через ЛК (Договор 5.8.8). Требует прав claims-оператора.
         */
        post: operations["decideTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/support/tickets/{id}/case-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Переход состояния разбирательства
         * @description Меняет case_state претензионного обращения. Недопустимые переходы → 422. Переход PAYOUT_PENDING → PAID требует подтверждения двумя сотрудниками (4 глаз).
         */
        post: operations["transitionCaseState"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/support/tickets/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Переписка по заявке
         * @description Внутренние заметки (is_internal) скрыты от заявителя на уровне хранилища.
         */
        get: operations["listMessages"];
        put?: never;
        /**
         * Добавить сообщение или внутреннюю заметку
         * @description is_internal=true → видно только операторам. Ответ заявителю доставляется по каналам уведомлений (ADR-0005).
         */
        post: operations["createMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/support/tickets/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Журнал действий по заявке (внутренний)
         * @description Неизменяемый журнал изменений заявки (§3.7). Только для операторов; заявителю — 403. Полный список без пагинации, в обратном хронологическом порядке (новые первыми).
         */
        get: operations["getTicketHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/support/tickets/{id}/requester-context": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Контекст заявителя (профиль/квартира/бронь)
         * @description Контекст заявителя для карточки оператора (FR-2.2): профиль, объект, бронь, коллаборант. Данные из rehome.one platform по HTTP. Только для операторов; заявителю — 403. Секции независимы и nullable (сущности нет либо сосед недоступен — graceful degradation, AT-003). Поле degraded=true означает, что интеграция с platform не сконфигурирована (см. #77), а не отсутствие конкретной сущности.
         */
        get: operations["getRequesterContext"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/support/tickets/{id}/suggested-articles": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Предложенные статьи базы знаний по заявке
         * @description Предлагает статьи kb-wiki по содержанию заявки через поиск kb-search (FR-5.4). Только для операторов; заявителю — 403; чужая/несуществующая — 404. Read-only. `degraded=true` означает, что интеграция с kb-search не сконфигурирована (#77) или недоступна (AT-003) — список пуст, не ошибка.
         */
        get: operations["getSuggestedArticles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/support/tickets/from-chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Создать заявку из эскалации AI-чата
         * @description Вызывается kb-search при эскалации диалога на оператора. Создаёт Ticket с channel=AI_CHAT, сохраняет chat_session_id и transcript. m2m-доступ (BearerAuth).
         */
        post: operations["createTicketFromChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/support/tickets/from-web-form": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Создать заявку через веб-форму ЛК
         * @description Создание заявки заявителем через веб-форму в личном кабинете rehome.one (FR-1.3, ADR-0010 Решение 2). Только аутентифицированный заявитель (kind=REQUESTER); requester_id и channel=WEB_FORM форсятся сервером (в теле не принимаются — anti-spoofing). При непустых attachments создаётся начальное сообщение-носитель вложений. UI веб-формы — в ЛК (вне kb-support).
         */
        post: operations["createTicketFromWebForm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/support/tickets/from-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Принять входящее письмо (email-шлюз)
         * @description Приём входящего email от шлюза в контуре РФ (FR-1.2, ADR-0010 Решения 1/3/4). m2m-доступ (BearerAuth), только kind=SERVICE — отправитель НЕ доверяется и резолвится сервером из письма (anti-spoofing). Тело — base64-кодированное сырое RFC822-письмо (provisional contract). Поведение: при номере активной заявки в теме письмо добавляется ответом, иначе создаётся новая заявка channel=EMAIL; повторная доставка дедуплицируется по Message-ID. Во всех исходах (создано / добавлено к существующей / дедуп) возвращается 201 со ссылкой на заявку. Malformed-письмо принимается (флаг разбора в заявке), битый base64 → 400, превышение размера тела → 422.
         */
        post: operations["createTicketFromEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/support/canned-responses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список шаблонов ответов
         * @description Доступно операторам (для вставки шаблона, FR-2.5). Bounded curated-набор — список целиком, без курсор-пагинации (как SLA/automation, ADR-0009).
         */
        get: operations["listCannedResponses"];
        put?: never;
        /**
         * Создать шаблон
         * @description scope=staff_support
         */
        post: operations["createCannedResponse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/support/canned-responses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Шаблон ответа
         * @description Доступно операторам.
         */
        get: operations["getCannedResponse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Изменить шаблон
         * @description scope=staff_support
         */
        patch: operations["updateCannedResponse"];
        trace?: never;
    };
    "/api/v1/support/canned-responses/{id}/render": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Отрендерить шаблон для заявки
         * @description Подставляет переменные шаблона по заявке (рендер на сервере — ПДн не на фронт). Доступно операторам. Локальные переменные ({{ticket_number}}, {{ticket_subject}}, {{ticket_type}}, {{current_date}}) — всегда; {{requester_name}} — из platform (config-gated, #77): при выключенной интеграции токен остаётся незаполненным.
         */
        post: operations["renderCannedResponse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/support/sla-policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список SLA-политик
         * @description scope=staff_admin. Включает неактивные политики (admin-конфигурация).
         */
        get: operations["listSLAPolicies"];
        put?: never;
        /**
         * Создать SLA-политику
         * @description scope=staff_admin
         */
        post: operations["createSLAPolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/support/sla-policies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * SLA-политика
         * @description scope=staff_admin
         */
        get: operations["getSLAPolicy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Изменить SLA-политику
         * @description scope=staff_admin
         */
        patch: operations["updateSLAPolicy"];
        trace?: never;
    };
    "/api/v1/support/business-hours": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список графиков рабочего времени
         * @description scope=staff_admin. Включает неактивные графики.
         */
        get: operations["listBusinessHours"];
        put?: never;
        /**
         * Создать график рабочего времени
         * @description scope=staff_admin
         */
        post: operations["createBusinessHours"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/support/business-hours/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * График рабочего времени
         * @description scope=staff_admin
         */
        get: operations["getBusinessHours"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Изменить график рабочего времени
         * @description scope=staff_admin
         */
        patch: operations["updateBusinessHours"];
        trace?: never;
    };
    "/api/v1/support/automation-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список правил автоматизации
         * @description scope=staff_admin. Включает неактивные правила (admin-конфигурация).
         */
        get: operations["listAutomationRules"];
        put?: never;
        /**
         * Создать правило
         * @description scope=staff_admin. Триггер → условия → действия.
         */
        post: operations["createAutomationRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/support/automation-rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Правило автоматизации
         * @description scope=staff_admin
         */
        get: operations["getAutomationRule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Изменить правило автоматизации
         * @description scope=staff_admin
         */
        patch: operations["updateAutomationRule"];
        trace?: never;
    };
    "/api/v1/support/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Метрики поддержки
         * @description Сводные метрики за период для панели супервайзера и дашборда Grafana. scope=staff_supervisor (оператор без него → 403). Период — UTC, from/to включительно; без параметров — последние 30 дней.
         */
        get: operations["getSupportStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/support/reports/{type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Отчёт
         * @description Готовые отчёты: объём по типам/каналам, SLA, удовлетворённость, повторные обращения, эффективность операторов. scope=staff_supervisor (оператор → 403). Период — UTC, from/to включительно; без параметров — последние 30 дней. volume агрегирует за окно запроса (time-series разбивка — отдельный follow-up). format=json отдаёт типизированный отчёт (по report-дискриминатору), format=csv — text/csv.
         */
        get: operations["getReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/support/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список подписок */
        get: operations["listWebhooks"];
        put?: never;
        /**
         * Зарегистрировать webhook
         * @description События доставляются с HMAC-подписью (заголовок X-Signature). scope=staff_admin.
         */
        post: operations["createWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Ошибка в формате RFC 7807 (problem+json) */
        Error: {
            /**
             * Format: uri
             * @example https://api.rehome.one/errors/validation
             */
            type: string;
            /** @example Validation failed */
            title: string;
            /** @example 422 */
            status: number;
            detail?: string;
            instance?: string;
            errors?: {
                field?: string;
                message?: string;
            }[];
        };
        Pagination: {
            /** @description Курсор следующей страницы (null если конец) */
            next_cursor?: string | null;
            has_more?: boolean;
        };
        /** @description Общий конверт успешного ответа */
        ResponseEnvelope: {
            /** @description Полезная нагрузка (объект или массив) */
            data?: unknown;
            /** Format: uuid */
            request_id?: string;
        };
        /**
         * @description NEW — новое; OPEN — в работе; PENDING — ждёт заявителя; WAITING — ждёт третью сторону (коллаборант/юрист/банк); ESCALATED — на 2-й линии; RESOLVED — решено, ждёт подтверждения; CLOSED — закрыто; REOPENED — переоткрыто
         * @enum {string}
         */
        TicketStatus: "NEW" | "OPEN" | "PENDING" | "WAITING" | "ESCALATED" | "RESOLVED" | "CLOSED" | "REOPENED";
        /** @enum {string} */
        TicketPriority: "low" | "normal" | "high" | "critical";
        /**
         * @description Тип обращения под предметную область аренды (раздел 3.3 ТЗ)
         * @enum {string}
         */
        TicketType: "PAYMENT" | "CONTRACT" | "MOVE_IN" | "MOVE_OUT" | "MAINTENANCE" | "UTILITIES" | "ACCOUNT" | "LISTING" | "COLLABORATOR" | "COMPLAINT" | "FRAUD" | "COMPENSATION" | "GUARANTEE" | "INSURANCE" | "ACCEPTANCE_ACT" | "OTHER";
        /**
         * @description Канал поступления. AI_CHAT — главный (эскалация из kb-search). LK_CLAIM/INSURER_WEBHOOK/SYSTEM — для претензионных типов (v1.1)
         * @enum {string}
         */
        TicketChannel: "AI_CHAT" | "EMAIL" | "WEB_FORM" | "PHONE" | "INTERNAL" | "LK_CLAIM" | "INSURER_WEBHOOK" | "SYSTEM";
        /**
         * @description Команда обработки
         * @enum {string}
         */
        TicketTeam: "support" | "legal" | "finance";
        /**
         * @description Состояние разбирательства претензионного обращения (раздел 3.2.1 ТЗ)
         * @enum {string}
         */
        TicketCaseState: "CLAIM_SUBMITTED" | "DOCS_PENDING" | "UNDER_REVIEW" | "INSPECTION" | "DECISION_MADE" | "PAYOUT_PENDING" | "PAID" | "REJECTED";
        /**
         * @description Решение по претензии (Договор 5.8.8)
         * @enum {string}
         */
        TicketDecision: "FULL" | "PARTIAL" | "REJECTED";
        /**
         * @description Тип акта приёма-передачи
         * @enum {string}
         */
        ActKind: "MOVE_IN" | "MOVE_OUT";
        /**
         * @description Статус подписания акта
         * @enum {string}
         */
        SigningStatus: "one_signed" | "both_signed" | "disputed";
        /** @enum {string} */
        AuthorType: "requester" | "operator" | "system" | "ai";
        /**
         * @description Состояние SLA для индикации (FR-4.3): none — без SLA; ok — в норме; approaching — осталось <20% временного окна; breached — дедлайн нарушен. Комбинация (худшее) дедлайнов первого ответа и решения; учитывает паузу.
         * @enum {string}
         */
        SlaState: "none" | "ok" | "approaching" | "breached";
        /** @description Краткая карточка заявки (для списков) */
        TicketSummary: {
            /** Format: uuid */
            id: string;
            /**
             * @description Человекочитаемый номер
             * @example RH-2026-00042
             */
            number: string;
            subject: string;
            status: components["schemas"]["TicketStatus"];
            priority: components["schemas"]["TicketPriority"];
            type: components["schemas"]["TicketType"];
            channel: components["schemas"]["TicketChannel"];
            /** Format: uuid */
            requester_id?: string;
            /** Format: uuid */
            assignee_id?: string | null;
            team?: components["schemas"]["TicketTeam"] | null;
            /** Format: date-time */
            first_response_due_at?: string | null;
            /** Format: date-time */
            resolution_due_at?: string | null;
            /** @description Нарушен ли дедлайн решения (расчётное поле; учитывает паузу и факт решения) */
            sla_breached?: boolean;
            sla_state?: components["schemas"]["SlaState"];
            tags?: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
        };
        Ticket: components["schemas"]["TicketSummary"] & {
            /** @description Статусы, в которые разрешён переход из текущего (машина состояний §3.2) */
            readonly allowed_status_transitions?: components["schemas"]["TicketStatus"][];
            /** @description Первичное описание проблемы */
            description?: string;
            /**
             * Format: uuid
             * @description Связанная квартира
             */
            premises_id?: string | null;
            /**
             * Format: uuid
             * @description Связанный договор/бронь
             */
            booking_id?: string | null;
            /** Format: uuid */
            collaborator_id?: string | null;
            /**
             * Format: uuid
             * @description Связанный заказ коллаборанту (ADR-0005: разные сущности по ссылке)
             */
            service_order_id?: string | null;
            /**
             * Format: uuid
             * @description Сессия AI-чата, откуда эскалировано
             */
            chat_session_id?: string | null;
            /** Format: uuid */
            sla_policy_id?: string | null;
            /** Format: date-time */
            first_responded_at?: string | null;
            /** Format: date-time */
            resolved_at?: string | null;
            /** Format: date-time */
            closed_at?: string | null;
            /** @default 0 */
            reopened_count: number;
            custom_fields?: {
                [key: string]: unknown;
            };
            /**
             * @description Контур доступа (ADR-0003). Обычно LOGGED
             * @enum {string}
             */
            access_level?: "PUBLIC" | "LOGGED" | "AGENT" | "STAFF" | "LEGAL" | "HR_RESTRICTED";
            rating?: number | null;
            rating_comment?: string | null;
            /** @description Состояние разбирательства (для претензионных типов) */
            case_state?: components["schemas"]["TicketCaseState"] | null;
            /** @description Заявленная сумма ущерба (COMPENSATION) */
            claim_amount?: number | null;
            /** @description Утверждённая к выплате сумма */
            approved_amount?: number | null;
            decision?: components["schemas"]["TicketDecision"] | null;
            /** @description Мотивировка (обязательна при PARTIAL/REJECTED) */
            decision_reason?: string | null;
            /** Format: date-time */
            decision_notified_at?: string | null;
            /**
             * Format: date-time
             * @description Дедлайн выплаты (не более 10 рабочих дней)
             */
            payout_due_at?: string | null;
            /** Format: uuid */
            linked_payment_id?: string | null;
            /** Format: uuid */
            regress_obligation_id?: string | null;
            /** Format: uuid */
            policy_id?: string | null;
            /** Format: uuid */
            insurance_event_id?: string | null;
            /** Format: uuid */
            acceptance_act_id?: string | null;
            /** @description Тип-специфичные детали (раздел 3.11 ТЗ) */
            case_details?: components["schemas"]["TicketCaseDetails"] | null;
        };
        TicketCreate: {
            subject: string;
            description?: string;
            type: components["schemas"]["TicketType"];
            priority?: components["schemas"]["TicketPriority"];
            channel?: components["schemas"]["TicketChannel"];
            /**
             * Format: uuid
             * @description Если создаёт оператор от имени заявителя
             */
            requester_id?: string;
            /** Format: uuid */
            premises_id?: string;
            /** Format: uuid */
            booking_id?: string;
            tags?: string[];
            custom_fields?: {
                [key: string]: unknown;
            };
        };
        WebFormTicketCreate: {
            subject: string;
            type: components["schemas"]["TicketType"];
            description?: string;
            priority?: components["schemas"]["TicketPriority"];
            /** Format: uuid */
            premises_id?: string;
            /** Format: uuid */
            booking_id?: string;
            tags?: string[];
            /** @description file_id вложений, загруженных ЛК в kb-files */
            attachments?: string[];
        };
        /** @description Частичное обновление. Недопустимые переходы статуса → 422 */
        TicketUpdate: {
            subject?: string;
            status?: components["schemas"]["TicketStatus"];
            priority?: components["schemas"]["TicketPriority"];
            type?: components["schemas"]["TicketType"];
            team?: components["schemas"]["TicketTeam"];
            tags?: string[];
            custom_fields?: {
                [key: string]: unknown;
            };
        };
        TicketMessage: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            ticket_id: string;
            /** Format: uuid */
            author_id?: string | null;
            author_type: components["schemas"]["AuthorType"];
            body: string;
            /**
             * @description Внутренняя заметка. НЕ видна заявителю (инвариант ADR-0003)
             * @default false
             */
            is_internal: boolean;
            attachments?: string[];
            /** Format: date-time */
            created_at: string;
        };
        /** @description Неизменяемая строка журнала действий по заявке (§3.7) */
        TicketHistory: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            ticket_id: string;
            /**
             * Format: uuid
             * @description Кто совершил действие (sub из токена)
             */
            actor_id: string;
            /** @description Вид действия. Значения: created, status_changed, reassigned, priority_changed, type_changed, team_changed, tags_updated, message_added, rated */
            action: string;
            /** @description Значения до изменения в форме {"<поле>": <значение>}; null для события created */
            from_value?: {
                [key: string]: unknown;
            } | null;
            /** @description Значения после изменения в форме {"<поле>": <значение>} */
            to_value?: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            created_at: string;
        };
        /** @description Профиль заявителя (контекст оператору, FR-2.2) */
        RequesterUser: {
            /** Format: uuid */
            id: string;
            display_name: string;
            email?: string | null;
            phone?: string | null;
            role: string;
            is_active: boolean;
            /** Format: date-time */
            created_at?: string | null;
        };
        /** @description Объект (квартира/помещение) по заявке */
        RequesterPremises: {
            /** Format: uuid */
            id: string;
            address: string;
            kind: string;
            rooms?: number | null;
            area_m2?: number | null;
            /** Format: uuid */
            landlord_id?: string | null;
        };
        /** @description Бронь/договор найма по заявке */
        RequesterBooking: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            premises_id: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: uuid */
            landlord_id: string;
            status: string;
            /** Format: date */
            period_start: string;
            /** Format: date */
            period_end?: string | null;
            monthly_rent?: number | null;
        };
        /** @description Контакты коллаборанта */
        RequesterContact: {
            email?: string | null;
            phone?: string | null;
        };
        /** @description Коллаборант по заявке */
        RequesterCollaborator: {
            /** Format: uuid */
            id: string;
            name: string;
            category: string;
            contact?: components["schemas"]["RequesterContact"] | null;
            is_active: boolean;
        };
        /** @description Контекст заявителя на карточке оператора (FR-2.2). Секции независимы и nullable. degraded=true — интеграция с platform не сконфигурирована (см. #77), не про существование сущности. */
        RequesterContext: {
            user: components["schemas"]["RequesterUser"] | null;
            premises: components["schemas"]["RequesterPremises"] | null;
            booking: components["schemas"]["RequesterBooking"] | null;
            collaborator: components["schemas"]["RequesterCollaborator"] | null;
            degraded: boolean;
        };
        SuggestedArticle: {
            slug: string;
            title: string;
            url?: string | null;
        };
        /** @description Предложенные статьи БЗ по заявке (FR-5.4). degraded=true — kb-search не сконфигурирован (#77) или недоступен (AT-003); список пуст, не ошибка. */
        SuggestedArticlesResult: {
            articles: components["schemas"]["SuggestedArticle"][];
            degraded: boolean;
        };
        TicketMessageCreate: {
            body: string;
            /** @default false */
            is_internal: boolean;
            attachments?: string[];
            /**
             * Format: uuid
             * @description Если ответ из шаблона — для учёта usage_count
             */
            canned_response_id?: string;
        };
        /** @description Создание заявки из эскалации AI-чата kb-search */
        TicketFromChat: {
            /** Format: uuid */
            chat_session_id: string;
            /** Format: uuid */
            requester_id: string;
            /** @description Если не задано — генерируется из диалога */
            subject?: string;
            type?: components["schemas"]["TicketType"];
            /** @description История диалога для контекста оператора */
            transcript?: {
                /** @enum {string} */
                role?: "user" | "assistant";
                content?: string;
                /** Format: date-time */
                at?: string;
            }[];
            /** Format: uuid */
            premises_id?: string;
            /** Format: uuid */
            booking_id?: string;
        };
        /** @description Приём входящего письма (E7-3). raw_message — base64-кодированное сырое RFC822-письмо (provisional contract: JSON-safe носитель байтов). */
        EmailIngest: {
            /** @description base64-кодированное сырое RFC822-письмо */
            raw_message: string;
        };
        CannedResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            /** @description Текст с переменными {{requester_name}}, {{ticket_number}} */
            body: string;
            type?: components["schemas"]["TicketType"] | null;
            /** @description Связанная статья kb-wiki */
            linked_article_slug?: string | null;
            /** @default 0 */
            usage_count: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CannedResponseInput: {
            title: string;
            body: string;
            type?: components["schemas"]["TicketType"];
            linked_article_slug?: string;
        };
        /** @description Частичное обновление шаблона (PATCH) — все поля опциональны. */
        CannedResponseUpdate: {
            title?: string;
            body?: string;
            type?: components["schemas"]["TicketType"] | null;
            linked_article_slug?: string | null;
        };
        CannedRenderInput: {
            /**
             * Format: uuid
             * @description Заявка, по которой подставляются переменные.
             */
            ticket_id: string;
        };
        CannedRenderResult: {
            /** @description Текст шаблона с подставленными переменными (неизвестные — как есть). */
            rendered_body: string;
            /** @description Связанная статья kb-wiki (для вставки ссылки оператором). */
            linked_article_slug?: string | null;
        };
        /** @description Условия применения SLA-политики (пустой объект = применима ко всем) */
        SLAAppliesTo: {
            types?: components["schemas"]["TicketType"][];
            priorities?: components["schemas"]["TicketPriority"][];
            requester_roles?: string[];
        };
        SLAPolicy: {
            /** Format: uuid */
            id: string;
            name: string;
            applies_to: components["schemas"]["SLAAppliesTo"];
            first_response_minutes: number;
            resolution_minutes: number;
            /**
             * Format: uuid
             * @description График (рабочие часы / 24-7 при null)
             */
            business_hours_id?: string | null;
            /** @description Приоритет применения при пересечении условий */
            priority: number;
            is_active: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        SLAPolicyInput: {
            name: string;
            applies_to?: components["schemas"]["SLAAppliesTo"];
            first_response_minutes: number;
            resolution_minutes: number;
            /** Format: uuid */
            business_hours_id?: string | null;
            priority?: number;
        };
        /** @description Частичное обновление SLA-политики (переданные поля) */
        SLAPolicyUpdate: {
            name?: string;
            applies_to?: components["schemas"]["SLAAppliesTo"];
            first_response_minutes?: number;
            resolution_minutes?: number;
            /** Format: uuid */
            business_hours_id?: string | null;
            priority?: number;
            is_active?: boolean;
        };
        /** @description Недельный график: день → массив интервалов рабочего времени. Интервал — пара ["HH:MM", "HH:MM"] (24ч, open < close). Отсутствующий день или пустой массив = выходной. */
        WeeklySchedule: {
            mon?: components["schemas"]["DayIntervals"];
            tue?: components["schemas"]["DayIntervals"];
            wed?: components["schemas"]["DayIntervals"];
            thu?: components["schemas"]["DayIntervals"];
            fri?: components["schemas"]["DayIntervals"];
            sat?: components["schemas"]["DayIntervals"];
            sun?: components["schemas"]["DayIntervals"];
        };
        /** @description Интервалы рабочего времени за день */
        DayIntervals: string[][];
        BusinessHours: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description IANA-таймзона (напр. Europe/Moscow) */
            timezone: string;
            schedule: components["schemas"]["WeeklySchedule"];
            is_active: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        BusinessHoursInput: {
            name: string;
            /** @description IANA-таймзона (напр. Europe/Moscow) */
            timezone: string;
            schedule?: components["schemas"]["WeeklySchedule"];
        };
        /** @description Частичное обновление графика (переданные поля) */
        BusinessHoursUpdate: {
            name?: string;
            timezone?: string;
            schedule?: components["schemas"]["WeeklySchedule"];
            is_active?: boolean;
        };
        /** @enum {string} */
        AutomationTrigger: "on_create" | "on_update" | "on_sla_breach" | "time_based";
        /** @description Условия применения правила (конъюнкция). Отсутствует/пусто = wildcard; пустой объект = ко всем заявкам триггера. keywords — подстрочный case-insensitive матчинг по subject/description. Статич. измерения (types/priorities/channels/statuses/keywords) применимы ко всем триггерам. Временные пороги (inactive_minutes/unanswered_minutes) применимы ТОЛЬКО при trigger=time_based и вычисляются периодическим сканом (источник истины — БД). */
        AutomationConditions: {
            types?: components["schemas"]["TicketType"][];
            priorities?: components["schemas"]["TicketPriority"][];
            channels?: components["schemas"]["TicketChannel"][];
            statuses?: components["schemas"]["TicketStatus"][];
            keywords?: string[];
            /** @description time_based: заявка без активности (по updated_at) не менее N минут. Допустимо только при trigger=time_based. */
            inactive_minutes?: number;
            /** @description time_based: заявка без первого ответа (first_responded_at IS NULL) и создана не менее N минут назад. Допустимо только при trigger=time_based. */
            unanswered_minutes?: number;
        };
        AssignActionParams: {
            /** @enum {string} */
            strategy: "direct" | "round_robin" | "least_load";
            /**
             * Format: uuid
             * @description Требуется при strategy=direct.
             */
            operator_id?: string;
            team?: components["schemas"]["TicketTeam"];
            /** @description Явный пул операторов (seam до platform-источника, #77). */
            pool?: string[];
        };
        SetStatusActionParams: {
            status: components["schemas"]["TicketStatus"];
        };
        SetPriorityActionParams: {
            priority: components["schemas"]["TicketPriority"];
        };
        AddTagActionParams: {
            tags: string[];
        };
        EscalateActionParams: {
            team?: components["schemas"]["TicketTeam"];
        };
        /** @description seam: доставка уведомлений — E7 (config-gated, ADR-0008 Реш.3). */
        NotifyActionParams: {
            /** @enum {string} */
            recipient: "requester" | "assignee" | "supervisor" | "team";
            channel?: string;
            template?: string;
        };
        /** @description seam: заказ коллаборанта — platform/#77 (config-gated). */
        CreateServiceOrderActionParams: {
            collaborator_category?: string;
            /** Format: uuid */
            premises_id?: string;
        };
        AssignAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "assign";
            params: components["schemas"]["AssignActionParams"];
        };
        SetStatusAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "set_status";
            params: components["schemas"]["SetStatusActionParams"];
        };
        SetPriorityAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "set_priority";
            params: components["schemas"]["SetPriorityActionParams"];
        };
        AddTagAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "add_tag";
            params: components["schemas"]["AddTagActionParams"];
        };
        EscalateAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "escalate";
            params: components["schemas"]["EscalateActionParams"];
        };
        NotifyAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "notify";
            params: components["schemas"]["NotifyActionParams"];
        };
        CreateServiceOrderAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "create_service_order";
            params: components["schemas"]["CreateServiceOrderActionParams"];
        };
        AutomationAction: components["schemas"]["AssignAction"] | components["schemas"]["SetStatusAction"] | components["schemas"]["SetPriorityAction"] | components["schemas"]["AddTagAction"] | components["schemas"]["EscalateAction"] | components["schemas"]["NotifyAction"] | components["schemas"]["CreateServiceOrderAction"];
        AutomationRule: {
            /** Format: uuid */
            id: string;
            name: string;
            trigger: components["schemas"]["AutomationTrigger"];
            conditions: components["schemas"]["AutomationConditions"];
            actions: components["schemas"]["AutomationAction"][];
            /** @default true */
            is_active: boolean;
            /** @description Порядок применения (asc; конфликт = last-write-wins). */
            order: number;
        };
        AutomationRuleInput: {
            name: string;
            trigger: components["schemas"]["AutomationTrigger"];
            conditions?: components["schemas"]["AutomationConditions"];
            actions: components["schemas"]["AutomationAction"][];
            /** @default true */
            is_active: boolean;
            /** @default 0 */
            order: number;
        };
        /** @description Частичное обновление правила (только переданные поля). */
        AutomationRuleUpdate: {
            name?: string;
            trigger?: components["schemas"]["AutomationTrigger"];
            conditions?: components["schemas"]["AutomationConditions"];
            actions?: components["schemas"]["AutomationAction"][];
            is_active?: boolean;
            order?: number;
        };
        SupportStats: {
            period?: {
                /** Format: date */
                from?: string;
                /** Format: date */
                to?: string;
            };
            tickets?: {
                total?: number;
                open?: number;
                resolved?: number;
                closed?: number;
                by_type?: {
                    [key: string]: number;
                };
                by_channel?: {
                    [key: string]: number;
                };
            };
            sla?: {
                first_response_compliance_pct?: number | null;
                resolution_compliance_pct?: number | null;
                breaches?: number;
            };
            performance?: {
                avg_first_response_minutes?: number | null;
                avg_resolution_minutes?: number | null;
                reopened_rate_pct?: number | null;
            };
            quality?: {
                avg_rating?: number | null;
                ratings_count?: number;
            };
            /** @description Метрики первой линии (kb-search) */
            ai_chat?: {
                /** @description Доля диалогов без эскалации (null — kb-search недоступен/выключен) */
                containment_rate_pct?: number | null;
                escalated_count?: number;
                /** @description containment недоступен (kb-search seam выключен/деградация) */
                degraded?: boolean;
            };
        };
        ReportPeriod: {
            /** Format: date */
            from?: string;
            /** Format: date */
            to?: string;
        };
        /** @description Объём заявок по типам и каналам за период (long-format строки). */
        VolumeReport: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            report: "volume";
            period?: components["schemas"]["ReportPeriod"];
            rows?: {
                /** @description Измерение: type | channel */
                dimension?: string;
                key?: string;
                count?: number;
            }[];
        };
        /** @description Соблюдение SLA за период (одна сводная строка). */
        SlaReport: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            report: "sla";
            period?: components["schemas"]["ReportPeriod"];
            rows?: {
                first_response_compliance_pct?: number | null;
                resolution_compliance_pct?: number | null;
                breaches?: number;
            }[];
        };
        /** @description Распределение оценок (1..5) за период. */
        SatisfactionReport: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            report: "satisfaction";
            period?: components["schemas"]["ReportPeriod"];
            rows?: {
                rating?: number;
                count?: number;
            }[];
        };
        /** @description Повторные обращения за период (одна сводная строка). */
        ReopensReport: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            report: "reopens";
            period?: components["schemas"]["ReportPeriod"];
            rows?: {
                total?: number;
                reopened?: number;
                reopened_rate_pct?: number | null;
            }[];
        };
        /** @description Эффективность операторов (resolved-anchor) за период. */
        OperatorsReport: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            report: "operators";
            period?: components["schemas"]["ReportPeriod"];
            rows?: {
                /** Format: uuid */
                operator_id?: string;
                resolved_count?: number;
                avg_resolution_minutes?: number | null;
            }[];
        };
        /** @description Детали претензионного обращения (1:1 с Ticket, раздел 3.11 ТЗ) */
        TicketCaseDetails: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            ticket_id?: string;
            /** @enum {string} */
            case_type: "COMPENSATION" | "GUARANTEE" | "INSURANCE" | "ACCEPTANCE_ACT";
            act_kind?: components["schemas"]["ActKind"] | null;
            signing_status?: components["schemas"]["SigningStatus"] | null;
            /** @description Структура по типу (валидируется схемой на стороне сервиса) */
            payload?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        WebhookSubscription: {
            /** Format: uuid */
            id?: string;
            /** Format: uri */
            url: string;
            events: ("ticket.created" | "ticket.updated" | "ticket.assigned" | "ticket.escalated" | "ticket.resolved" | "ticket.closed" | "ticket.reopened" | "ticket.message_added" | "ticket.sla_breached" | "ticket.rated" | "ticket.case_decided" | "ticket.payout_released" | "ticket.insurance_event")[];
            /** @description Секрет для HMAC-подписи (только при создании) */
            secret?: string;
            /** @default true */
            is_active: boolean;
        };
    };
    responses: {
        /** @description Некорректный запрос */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Error"];
            };
        };
        /** @description Не аутентифицирован */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Error"];
            };
        };
        /** @description Нет прав (scope недостаточен) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Error"];
            };
        };
        /** @description Не найдено (или недоступно по access_level — 404 вместо 403, ADR-0003) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Error"];
            };
        };
        /** @description Конфликт (например, недопустимый переход статуса) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Error"];
            };
        };
        /** @description Ошибка валидации */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Идентификатор запроса для трассировки */
        RequestId: string;
        /** @description Ключ идемпотентности для безопасного повтора POST */
        IdempotencyKey: string;
        /** @description CSRF-токен для браузерных сессий (CookieAuth) */
        CsrfToken: string;
        /** @description Курсор для пагинации (из предыдущего ответа) */
        Cursor: string;
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listTickets: {
        parameters: {
            query?: {
                status?: components["schemas"]["TicketStatus"];
                type?: components["schemas"]["TicketType"];
                priority?: components["schemas"]["TicketPriority"];
                channel?: components["schemas"]["TicketChannel"];
                assignee_id?: string;
                requester_id?: string;
                team?: components["schemas"]["TicketTeam"];
                premises_id?: string;
                sla_breached?: boolean;
                tag?: string;
                sort?: "created_at" | "-created_at" | "resolution_due_at" | "-resolution_due_at" | "priority" | "-priority";
                /** @description Курсор для пагинации (из предыдущего ответа) */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: {
                /** @description Идентификатор запроса для трассировки */
                "X-Request-Id"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["TicketSummary"][];
                        pagination?: components["schemas"]["Pagination"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createTicket: {
        parameters: {
            query?: never;
            header?: {
                /** @description Идентификатор запроса для трассировки */
                "X-Request-Id"?: components["parameters"]["RequestId"];
                /** @description Ключ идемпотентности для безопасного повтора POST */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                /** @description CSRF-токен для браузерных сессий (CookieAuth) */
                "X-CSRF-Token"?: components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketCreate"];
            };
        };
        responses: {
            /** @description Создано */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["Ticket"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["Ticket"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateTicket: {
        parameters: {
            query?: never;
            header?: {
                /** @description CSRF-токен для браузерных сессий (CookieAuth) */
                "X-CSRF-Token"?: components["parameters"]["CsrfToken"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["Ticket"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    assignTicket: {
        parameters: {
            query?: never;
            header?: {
                /** @description CSRF-токен для браузерных сессий (CookieAuth) */
                "X-CSRF-Token"?: components["parameters"]["CsrfToken"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    assignee_id: string;
                    team?: components["schemas"]["TicketTeam"] | null;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["Ticket"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    escalateTicket: {
        parameters: {
            query?: never;
            header?: {
                /** @description CSRF-токен для браузерных сессий (CookieAuth) */
                "X-CSRF-Token"?: components["parameters"]["CsrfToken"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    team?: components["schemas"]["TicketTeam"] | null;
                    reason?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["Ticket"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    resolveTicket: {
        parameters: {
            query?: never;
            header?: {
                /** @description CSRF-токен для браузерных сессий (CookieAuth) */
                "X-CSRF-Token"?: components["parameters"]["CsrfToken"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    resolution_note?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["Ticket"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    closeTicket: {
        parameters: {
            query?: never;
            header?: {
                /** @description CSRF-токен для браузерных сессий (CookieAuth) */
                "X-CSRF-Token"?: components["parameters"]["CsrfToken"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["Ticket"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    reopenTicket: {
        parameters: {
            query?: never;
            header?: {
                /** @description CSRF-токен для браузерных сессий (CookieAuth) */
                "X-CSRF-Token"?: components["parameters"]["CsrfToken"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    reason?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["Ticket"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    rateTicket: {
        parameters: {
            query?: never;
            header?: {
                /** @description CSRF-токен для браузерных сессий (CookieAuth) */
                "X-CSRF-Token"?: components["parameters"]["CsrfToken"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    rating: number;
                    comment?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["Ticket"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    decideTicket: {
        parameters: {
            query?: never;
            header?: {
                /** @description Ключ идемпотентности для безопасного повтора POST */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                /** @description CSRF-токен для браузерных сессий (CookieAuth) */
                "X-CSRF-Token"?: components["parameters"]["CsrfToken"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    decision: components["schemas"]["TicketDecision"];
                    /** @description Обязательно при FULL/PARTIAL */
                    approved_amount?: number;
                    /** @description Мотивировка (обязательна при PARTIAL/REJECTED) */
                    reason?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["Ticket"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    transitionCaseState: {
        parameters: {
            query?: never;
            header?: {
                /** @description CSRF-токен для браузерных сессий (CookieAuth) */
                "X-CSRF-Token"?: components["parameters"]["CsrfToken"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    case_state: components["schemas"]["TicketCaseState"];
                    note?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["Ticket"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    listMessages: {
        parameters: {
            query?: {
                /** @description Курсор для пагинации (из предыдущего ответа) */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["TicketMessage"][];
                        pagination?: components["schemas"]["Pagination"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createMessage: {
        parameters: {
            query?: never;
            header?: {
                /** @description Ключ идемпотентности для безопасного повтора POST */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                /** @description CSRF-токен для браузерных сессий (CookieAuth) */
                "X-CSRF-Token"?: components["parameters"]["CsrfToken"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketMessageCreate"];
            };
        };
        responses: {
            /** @description Создано */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["TicketMessage"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getTicketHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["TicketHistory"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getRequesterContext: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["RequesterContext"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getSuggestedArticles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["SuggestedArticlesResult"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createTicketFromChat: {
        parameters: {
            query?: never;
            header?: {
                /** @description Идентификатор запроса для трассировки */
                "X-Request-Id"?: components["parameters"]["RequestId"];
                /** @description Ключ идемпотентности для безопасного повтора POST */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketFromChat"];
            };
        };
        responses: {
            /** @description Заявка создана */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["Ticket"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    createTicketFromWebForm: {
        parameters: {
            query?: never;
            header?: {
                /** @description Идентификатор запроса для трассировки */
                "X-Request-Id"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebFormTicketCreate"];
            };
        };
        responses: {
            /** @description Заявка создана */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["Ticket"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    createTicketFromEmail: {
        parameters: {
            query?: never;
            header?: {
                /** @description Идентификатор запроса для трассировки */
                "X-Request-Id"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailIngest"];
            };
        };
        responses: {
            /** @description Заявка создана, дополнена или дедуплицирована (ссылка на заявку) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["Ticket"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    listCannedResponses: {
        parameters: {
            query?: {
                type?: components["schemas"]["TicketType"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["CannedResponse"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createCannedResponse: {
        parameters: {
            query?: never;
            header?: {
                /** @description CSRF-токен для браузерных сессий (CookieAuth) */
                "X-CSRF-Token"?: components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CannedResponseInput"];
            };
        };
        responses: {
            /** @description Создано */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["CannedResponse"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getCannedResponse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["CannedResponse"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateCannedResponse: {
        parameters: {
            query?: never;
            header?: {
                /** @description CSRF-токен для браузерных сессий (CookieAuth) */
                "X-CSRF-Token"?: components["parameters"]["CsrfToken"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CannedResponseUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["CannedResponse"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    renderCannedResponse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CannedRenderInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["CannedRenderResult"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listSLAPolicies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["SLAPolicy"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createSLAPolicy: {
        parameters: {
            query?: never;
            header?: {
                /** @description CSRF-токен для браузерных сессий (CookieAuth) */
                "X-CSRF-Token"?: components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SLAPolicyInput"];
            };
        };
        responses: {
            /** @description Создано */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["SLAPolicy"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getSLAPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["SLAPolicy"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateSLAPolicy: {
        parameters: {
            query?: never;
            header?: {
                /** @description CSRF-токен для браузерных сессий (CookieAuth) */
                "X-CSRF-Token"?: components["parameters"]["CsrfToken"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SLAPolicyUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["SLAPolicy"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    listBusinessHours: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["BusinessHours"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createBusinessHours: {
        parameters: {
            query?: never;
            header?: {
                /** @description CSRF-токен для браузерных сессий (CookieAuth) */
                "X-CSRF-Token"?: components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BusinessHoursInput"];
            };
        };
        responses: {
            /** @description Создано */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["BusinessHours"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getBusinessHours: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["BusinessHours"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateBusinessHours: {
        parameters: {
            query?: never;
            header?: {
                /** @description CSRF-токен для браузерных сессий (CookieAuth) */
                "X-CSRF-Token"?: components["parameters"]["CsrfToken"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BusinessHoursUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["BusinessHours"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    listAutomationRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["AutomationRule"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createAutomationRule: {
        parameters: {
            query?: never;
            header?: {
                /** @description CSRF-токен для браузерных сессий (CookieAuth) */
                "X-CSRF-Token"?: components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutomationRuleInput"];
            };
        };
        responses: {
            /** @description Создано */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["AutomationRule"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getAutomationRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["AutomationRule"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateAutomationRule: {
        parameters: {
            query?: never;
            header?: {
                /** @description CSRF-токен для браузерных сессий (CookieAuth) */
                "X-CSRF-Token"?: components["parameters"]["CsrfToken"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutomationRuleUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["AutomationRule"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getSupportStats: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["SupportStats"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getReport: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                format?: "json" | "csv";
            };
            header?: never;
            path: {
                type: "volume" | "sla" | "satisfaction" | "reopens" | "operators";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["VolumeReport"] | components["schemas"]["SlaReport"] | components["schemas"]["SatisfactionReport"] | components["schemas"]["ReopensReport"] | components["schemas"]["OperatorsReport"];
                    };
                    "text/csv": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    listWebhooks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["WebhookSubscription"][];
                        pagination?: components["schemas"]["Pagination"];
                    };
                };
            };
        };
    };
    createWebhook: {
        parameters: {
            query?: never;
            header?: {
                /** @description CSRF-токен для браузерных сессий (CookieAuth) */
                "X-CSRF-Token"?: components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookSubscription"];
            };
        };
        responses: {
            /** @description Создано */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope"] & {
                        data?: components["schemas"]["WebhookSubscription"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
}
